"""Compact, evidence-verifiable differences across cold-start re-entry packets.

The ledger indexes retained, added, missing, conflict, and head differences. It
does not embed full packets or replace them as evidence. Structural validation
checks the compact ledger; evidence verification regenerates it from retained
verified packets and their reconstruction sources.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Mapping, Sequence

from holosim.canonical import CanonicalValueError, stable_hash
from holosim.verified_cold_start_reentry_gateway import (
    VerifiedColdStartReentryError,
    validate_verified_cold_start_reentry_packet,
)


LEDGER_TYPE = "cold_start_retained_delta_ledger"
DELTA_TYPE = "cold_start_retained_delta"
VERSION = 1

LEDGER_FIELDS = {
    "type",
    "version",
    "ledger_id",
    "continuity_id",
    "entries",
    "head_delta_id",
    "head_packet_hash",
    "decision",
    "stop_condition",
    "truth_claimed",
    "accepted",
    "write_authority",
    "execution_authority",
    "interpretation_notice",
    "ledger_hash",
}

DELTA_FIELDS = {
    "type",
    "version",
    "delta_index",
    "previous_delta_id",
    "previous_packet_id",
    "previous_packet_hash",
    "current_packet_id",
    "current_packet_hash",
    "previous_status",
    "current_status",
    "previous_head",
    "current_head",
    "retained_item_ids",
    "added_item_ids",
    "missing_item_ids",
    "added_conflict_hashes",
    "resolved_conflict_hashes",
    "decision",
    "stop_condition",
    "truth_claimed",
    "accepted",
    "write_authority",
    "execution_authority",
    "interpretation_notice",
    "delta_id",
}

LEDGER_NOTICE = (
    "This compact ledger indexes differences between retained cold-start packets. "
    "It does not replace those packets, establish truth or acceptance, or grant "
    "write or execution authority."
)

DELTA_NOTICE = (
    "This delta is a non-authoritative summary. Its relationship to source packets "
    "is established only when regenerated by the external evidence verifier."
)


class ColdStartRetainedDeltaError(ValueError):
    """Raised when retained-delta structure or packet evidence fails closed."""


def _hash(value: Any) -> str:
    try:
        return stable_hash(value)
    except CanonicalValueError as exc:
        raise ColdStartRetainedDeltaError(str(exc)) from exc


def _text(value: Any, field: str) -> str:
    if type(value) is not str or not value.strip():
        raise ColdStartRetainedDeltaError(
            f"{field} must be a nonempty plain string"
        )
    try:
        value.encode("utf-8")
    except UnicodeError as exc:
        raise ColdStartRetainedDeltaError(f"{field} must be valid UTF-8") from exc
    return value


def _optional_text(value: Any, field: str) -> str | None:
    return None if value is None else _text(value, field)


def _authority_none(value: Mapping[str, Any], field: str) -> None:
    if (
        value.get("truth_claimed") is not False
        or value.get("accepted") is not False
        or value.get("write_authority") != "NONE"
        or value.get("execution_authority") != "NONE"
    ):
        raise ColdStartRetainedDeltaError(f"{field} cannot grant authority")


def _sorted_texts(value: Any, field: str) -> list[str]:
    if type(value) is not list:
        raise ColdStartRetainedDeltaError(f"{field} must be a list")
    checked = [_text(item, f"{field} item") for item in value]
    if checked != sorted(set(checked)):
        raise ColdStartRetainedDeltaError(
            f"{field} must contain sorted unique values"
        )
    return checked


def _packet_head(packet: Mapping[str, Any]) -> dict[str, Any]:
    head_check = packet["head_check"]
    return {
        "hash": head_check["current_head_hash"],
        "index": head_check["current_head_idx"],
    }


def _validate_packet(
    packet: Mapping[str, Any], source_items: Sequence[Mapping[str, Any]], field: str
) -> None:
    try:
        validate_verified_cold_start_reentry_packet(
            packet, source_items=source_items
        )
    except (VerifiedColdStartReentryError, KeyError, TypeError) as exc:
        raise ColdStartRetainedDeltaError(
            f"{field} packet evidence is invalid: {exc}"
        ) from exc


def _classification(
    *, current_status: str, current_decision: str, missing_item_ids: list[str]
) -> tuple[str, str | None]:
    if current_status != "READY_FOR_REENTRY" or current_decision != "ALLOW":
        return "STOP", "CURRENT_REENTRY_BLOCKED"
    if missing_item_ids:
        return "STOP", "RETENTION_LOSS_REQUIRES_REVIEW"
    return "CONTINUE", None


def _ledger_body(
    *,
    ledger_id: str,
    continuity_id: str,
    entries: list[dict[str, Any]],
    head_delta_id: str | None,
    head_packet_hash: str | None,
    decision: str,
    stop_condition: str | None,
) -> dict[str, Any]:
    return {
        "type": LEDGER_TYPE,
        "version": VERSION,
        "ledger_id": ledger_id,
        "continuity_id": continuity_id,
        "entries": deepcopy(entries),
        "head_delta_id": head_delta_id,
        "head_packet_hash": head_packet_hash,
        "decision": decision,
        "stop_condition": stop_condition,
        "truth_claimed": False,
        "accepted": False,
        "write_authority": "NONE",
        "execution_authority": "NONE",
        "interpretation_notice": LEDGER_NOTICE,
    }


def _finish_ledger(**values: Any) -> dict[str, Any]:
    body = _ledger_body(**values)
    return {**body, "ledger_hash": _hash(body)}


def build_cold_start_delta_ledger(
    *, ledger_id: str, continuity_id: str
) -> dict[str, Any]:
    """Build an empty deterministic retained-delta ledger."""
    return _finish_ledger(
        ledger_id=_text(ledger_id, "ledger_id"),
        continuity_id=_text(continuity_id, "continuity_id"),
        entries=[],
        head_delta_id=None,
        head_packet_hash=None,
        decision="CONTINUE",
        stop_condition=None,
    )


def _append_checked(
    *,
    ledger: Mapping[str, Any],
    previous_packet: Mapping[str, Any],
    previous_source_items: Sequence[Mapping[str, Any]],
    current_packet: Mapping[str, Any],
    current_source_items: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    _validate_packet(previous_packet, previous_source_items, "previous")
    _validate_packet(current_packet, current_source_items, "current")
    if (
        ledger["head_packet_hash"] is not None
        and ledger["head_packet_hash"] != previous_packet["packet_hash"]
    ):
        raise ColdStartRetainedDeltaError(
            "previous packet does not match the retained packet head"
        )

    previous_ids = set(previous_packet["carried_item_ids"])
    current_ids = set(current_packet["carried_item_ids"])
    retained = sorted(previous_ids & current_ids)
    added = sorted(current_ids - previous_ids)
    missing = sorted(previous_ids - current_ids)
    previous_conflicts = {_hash(item) for item in previous_packet["conflicts"]}
    current_conflicts = {_hash(item) for item in current_packet["conflicts"]}
    added_conflicts = sorted(current_conflicts - previous_conflicts)
    resolved_conflicts = sorted(previous_conflicts - current_conflicts)
    decision, stop_condition = _classification(
        current_status=current_packet["status"],
        current_decision=current_packet["gate_decision"],
        missing_item_ids=missing,
    )

    entries = deepcopy(ledger["entries"])
    body = {
        "type": DELTA_TYPE,
        "version": VERSION,
        "delta_index": len(entries) + 1,
        "previous_delta_id": ledger["head_delta_id"],
        "previous_packet_id": previous_packet["packet_id"],
        "previous_packet_hash": previous_packet["packet_hash"],
        "current_packet_id": current_packet["packet_id"],
        "current_packet_hash": current_packet["packet_hash"],
        "previous_status": previous_packet["status"],
        "current_status": current_packet["status"],
        "previous_head": _packet_head(previous_packet),
        "current_head": _packet_head(current_packet),
        "retained_item_ids": retained,
        "added_item_ids": added,
        "missing_item_ids": missing,
        "added_conflict_hashes": added_conflicts,
        "resolved_conflict_hashes": resolved_conflicts,
        "decision": decision,
        "stop_condition": stop_condition,
        "truth_claimed": False,
        "accepted": False,
        "write_authority": "NONE",
        "execution_authority": "NONE",
        "interpretation_notice": DELTA_NOTICE,
    }
    delta = {**body, "delta_id": _hash(body)}
    entries.append(delta)
    return _finish_ledger(
        ledger_id=ledger["ledger_id"],
        continuity_id=ledger["continuity_id"],
        entries=entries,
        head_delta_id=delta["delta_id"],
        head_packet_hash=current_packet["packet_hash"],
        decision=decision,
        stop_condition=stop_condition,
    )


def append_cold_start_delta(
    *,
    ledger: Mapping[str, Any],
    previous_packet: Mapping[str, Any],
    previous_source_items: Sequence[Mapping[str, Any]],
    current_packet: Mapping[str, Any],
    current_source_items: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Append one verified packet-to-packet difference without mutating inputs."""
    validate_cold_start_delta_ledger(ledger)
    return _append_checked(
        ledger=ledger,
        previous_packet=previous_packet,
        previous_source_items=previous_source_items,
        current_packet=current_packet,
        current_source_items=current_source_items,
    )


def _validate_delta(delta: Any, index: int, previous_delta_id: str | None) -> None:
    if type(delta) is not dict or set(delta) != DELTA_FIELDS:
        raise ColdStartRetainedDeltaError(
            "delta fields do not match the versioned schema"
        )
    if delta.get("type") != DELTA_TYPE or delta.get("version") != VERSION:
        raise ColdStartRetainedDeltaError("delta type or version is invalid")
    if delta.get("delta_index") != index:
        raise ColdStartRetainedDeltaError("delta index is not monotonic")
    if delta.get("previous_delta_id") != previous_delta_id:
        raise ColdStartRetainedDeltaError("delta lineage is invalid")
    _authority_none(delta, "delta")
    if delta.get("interpretation_notice") != DELTA_NOTICE:
        raise ColdStartRetainedDeltaError("delta interpretation_notice is invalid")
    _text(delta.get("previous_packet_id"), "previous_packet_id")
    _text(delta.get("previous_packet_hash"), "previous_packet_hash")
    _text(delta.get("current_packet_id"), "current_packet_id")
    _text(delta.get("current_packet_hash"), "current_packet_hash")
    retained = _sorted_texts(delta.get("retained_item_ids"), "retained_item_ids")
    added = _sorted_texts(delta.get("added_item_ids"), "added_item_ids")
    missing = _sorted_texts(delta.get("missing_item_ids"), "missing_item_ids")
    _sorted_texts(delta.get("added_conflict_hashes"), "added_conflict_hashes")
    _sorted_texts(
        delta.get("resolved_conflict_hashes"), "resolved_conflict_hashes"
    )
    if set(retained) & (set(added) | set(missing)) or set(added) & set(missing):
        raise ColdStartRetainedDeltaError("item delta classes must be disjoint")
    for field in ("previous_head", "current_head"):
        head = delta.get(field)
        if type(head) is not dict or set(head) != {"hash", "index"}:
            raise ColdStartRetainedDeltaError(f"{field} schema is invalid")
    expected_decision, expected_stop = _classification(
        current_status=delta.get("current_status"),
        current_decision=(
            "ALLOW" if delta.get("current_status") == "READY_FOR_REENTRY" else "BLOCK"
        ),
        missing_item_ids=missing,
    )
    if (
        delta.get("decision") != expected_decision
        or delta.get("stop_condition") != expected_stop
    ):
        raise ColdStartRetainedDeltaError("delta stop classification is invalid")
    body = dict(delta)
    claimed = body.pop("delta_id")
    if type(claimed) is not str or _hash(body) != claimed:
        raise ColdStartRetainedDeltaError("delta identity mismatch")


def validate_cold_start_delta_ledger(ledger: Mapping[str, Any]) -> bool:
    """Validate compact structure without claiming source-packet equivalence."""
    if type(ledger) is not dict:
        raise ColdStartRetainedDeltaError("ledger must be a plain dictionary")
    if set(ledger) != LEDGER_FIELDS:
        raise ColdStartRetainedDeltaError(
            "ledger fields do not match the versioned schema"
        )
    if ledger.get("type") != LEDGER_TYPE or ledger.get("version") != VERSION:
        raise ColdStartRetainedDeltaError("ledger type or version is invalid")
    _authority_none(ledger, "ledger")
    if ledger.get("interpretation_notice") != LEDGER_NOTICE:
        raise ColdStartRetainedDeltaError("ledger interpretation_notice is invalid")
    _text(ledger.get("ledger_id"), "ledger_id")
    _text(ledger.get("continuity_id"), "continuity_id")
    if type(ledger.get("entries")) is not list:
        raise ColdStartRetainedDeltaError("entries must be a list")

    body = dict(ledger)
    claimed_hash = body.pop("ledger_hash")
    if type(claimed_hash) is not str or _hash(body) != claimed_hash:
        raise ColdStartRetainedDeltaError("ledger hash mismatch")

    previous_delta_id = None
    previous_packet_hash = None
    for index, delta in enumerate(ledger["entries"], 1):
        _validate_delta(delta, index, previous_delta_id)
        if (
            previous_packet_hash is not None
            and delta["previous_packet_hash"] != previous_packet_hash
        ):
            raise ColdStartRetainedDeltaError("retained packet head is discontinuous")
        previous_delta_id = delta["delta_id"]
        previous_packet_hash = delta["current_packet_hash"]

    if ledger["entries"]:
        last = ledger["entries"][-1]
        expected = {
            "head_delta_id": last["delta_id"],
            "head_packet_hash": last["current_packet_hash"],
            "decision": last["decision"],
            "stop_condition": last["stop_condition"],
        }
    else:
        expected = {
            "head_delta_id": None,
            "head_packet_hash": None,
            "decision": "CONTINUE",
            "stop_condition": None,
        }
    if any(ledger.get(field) != value for field, value in expected.items()):
        raise ColdStartRetainedDeltaError("ledger head does not match delta history")
    return True


def verify_cold_start_delta_evidence(
    ledger: Mapping[str, Any], *, packet_evidence: Mapping[str, Mapping[str, Any]]
) -> bool:
    """Regenerate every compact delta from externally retained packet evidence."""
    validate_cold_start_delta_ledger(ledger)
    if type(packet_evidence) is not dict:
        raise ColdStartRetainedDeltaError(
            "packet_evidence must be a plain dictionary"
        )
    rebuilt = build_cold_start_delta_ledger(
        ledger_id=ledger["ledger_id"], continuity_id=ledger["continuity_id"]
    )
    for delta in ledger["entries"]:
        try:
            previous_evidence = packet_evidence[delta["previous_packet_hash"]]
            current_evidence = packet_evidence[delta["current_packet_hash"]]
        except KeyError as exc:
            raise ColdStartRetainedDeltaError(
                "packet evidence is missing for a retained delta"
            ) from exc
        for value, field in (
            (previous_evidence, "previous"),
            (current_evidence, "current"),
        ):
            if type(value) is not dict or set(value) != {"packet", "source_items"}:
                raise ColdStartRetainedDeltaError(
                    f"{field} packet evidence schema is invalid"
                )
        if (
            previous_evidence["packet"].get("packet_hash")
            != delta["previous_packet_hash"]
            or current_evidence["packet"].get("packet_hash")
            != delta["current_packet_hash"]
        ):
            raise ColdStartRetainedDeltaError(
                "packet evidence key does not match packet identity"
            )
        rebuilt = _append_checked(
            ledger=rebuilt,
            previous_packet=previous_evidence["packet"],
            previous_source_items=previous_evidence["source_items"],
            current_packet=current_evidence["packet"],
            current_source_items=current_evidence["source_items"],
        )
    if rebuilt != ledger:
        raise ColdStartRetainedDeltaError(
            "ledger does not match retained packet evidence"
        )
    return True